### PR TITLE
Changed GeodeticCRS to GeographicCRS (per issue #79) and expanded the…

### PR DESCRIPTION
**Pull request by jonblower**
… text explaining CRSs

#79

### CODE REVIEW

**Comment by letmaik** [comment]
Looks good, just two things.

1. In the VerticalCRS section you missed the two bullet points for the id and type properties.

2. You wrote:

> All reference system objects MUST have a member "type", which takes one of the values from the sections below.

This should mention the possibility of using custom types as well. Something like  "Custom reference system types may be used as recommended in the section "Extensions"." maybe.

**Comment by jonblower** [comment]
OK done - how does that look now?

**Comment by letmaik** [comment]
Hm, not sure, URI identifier doesn't make much sense to me, as it's Uniform Resource Identifier identifier. Apart from that, this is not the only way the value can be via an extension. It says "The custom value of those members [the "type" field here] SHOULD be either an absolute URI or a compact URI." When you search the spec for "extension" then you see several places where I already reference the extension mechanism for type fields. E.g. `The values of "dataType" defined in this specification are "primitive", "tuple", and "polygon". Custom values MAY be used as detailed in the "Extensions" section.` I think for CRS types it should be similar.

**Comment by jonblower** [comment]
OK, I edited this, and also edited some of the text around reference system connection objects. How does this look?

**Comment by letmaik** [comment]
OK, looks fine now. I'll merge it later together with changes to the examples in the playground etc.

**Pull request merged**
